//! # D-Bus interface proxy for: `net.connman.iwd.SimpleConfiguration`
//!
//! This code was generated by `zbus-xmlgen` `5.3.0` from D-Bus introspection data.
//! Source: `Interface '/net/connman/iwd/0/3' from service 'net.connman.iwd' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "net.connman.iwd.SimpleConfiguration",
    default_service = "net.connman.iwd",
    default_path = "/net/connman/iwd/0/3"
)]
pub trait SimpleConfiguration {
    /// Cancel method
    fn cancel(&self) -> zbus::Result<()>;

    /// GeneratePin method
    fn generate_pin(&self) -> zbus::Result<String>;

    /// PushButton method
    fn push_button(&self) -> zbus::Result<()>;

    /// StartPin method
    fn start_pin(&self, pin: &str) -> zbus::Result<()>;
}
